In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk
import re
# Before we begin, we supress deprecation warnings resulting from nltk
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning) 
pd.set_option('display.max_colwidth', -1) # Setting this so we can see the full content of cells

In [2]:
path = "G:/Learning/Projects/Data Science/Movie_review"
data = pd.read_csv(path+"/IMDB Dataset.csv")

In [5]:
print("The dataframe has {} rows and {} columns".format(data.shape[0], data.shape[1]))

The dataframe has 50000 rows and 2 columns


In [6]:
data.head()

review  \
0  One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.   
1  A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master's of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional 'dream' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell's murals decorating every surface) are terribly well done.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
2  I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). While some may be disappointed when they realize this is not Match Point 2: Risk Addiction, I thought it was proof that Woody Allen is still fully in control of the styl

In [8]:
input_ = [df.review[0]]
input_

# As we can see there a few Html tags, punctuations and capitalizations that need to be corrected

["One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the f

In [10]:
vectorizer_stop_words_only = CountVectorizer(stop_words = stopwords)

vec_stop_words = vectorizer_stop_words_only.fit_transform(input_)
print(vec_stop_words.shape)

vectorizer_stop_words_only.vocabulary_
#Earlier it was 186. So about 50 stop words have been removed

(1, 136)


{'one': 83,
 'reviewers': 97,
 'mentioned': 75,
 'watching': 132,
 'oz': 86,
 'episode': 31,
 'hooked': 58,
 'right': 98,
 'exactly': 33,
 'happened': 53,
 'br': 10,
 'first': 40,
 'thing': 121,
 'struck': 117,
 'brutality': 11,
 'unflinching': 127,
 'scenes': 102,
 'violence': 130,
 'set': 106,
 'word': 134,
 'go': 48,
 'trust': 124,
 'show': 109,
 'faint': 38,
 'hearted': 55,
 'timid': 122,
 'pulls': 93,
 'punches': 94,
 'regards': 96,
 'drugs': 27,
 'sex': 107,
 'hardcore': 54,
 'classic': 18,
 'use': 128,
 'called': 12,
 'nickname': 82,
 'given': 46,
 'oswald': 85,
 'maximum': 73,
 'security': 105,
 'state': 115,
 'penitentary': 88,
 'focuses': 41,
 'mainly': 69,
 'emerald': 30,
 'city': 16,
 'experimental': 35,
 'section': 104,
 'prison': 91,
 'cells': 13,
 'glass': 47,
 'fronts': 43,
 'face': 36,
 'inwards': 61,
 'privacy': 92,
 'high': 56,
 'agenda': 1,
 'em': 29,
 'home': 57,
 'many': 72,
 'aryans': 5,
 'muslims': 78,
 'gangstas': 44,
 'latinos': 66,
 'christians': 15,
 'italia

In [9]:
def custom_preprocessor(text):
    '''
    Make text lowercase, remove text in square brackets,remove links,remove special characters
    and remove words containing numbers.
    '''
    import string
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub("\\W"," ",text) # remove special chars
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    
    return text

In [12]:
#selecting just 1000 rows for quick performance

data_sample = data.sample(n=1000)

In [15]:
# Converting sentiment string to numbers
data['sentiment'] = data['sentiment'].map({'negative':0, 'positive':1})

In [16]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data['review'], data['sentiment'], test_size=0.5, random_state = 42)

In [17]:
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
stopwords = stopwords.words('english')

count_vectorizer = CountVectorizer(token_pattern=r'\w{1,}',
                   ngram_range=(1, 2), stop_words = stopwords,preprocessor=custom_preprocessor, min_df=10, max_df=0.8)
count_vectorizer.fit(x_train)

train_vectors = count_vectorizer.transform(x_train)
test_vectors = count_vectorizer.transform(x_test)

In [19]:
print("The number of unique tokens are: ", len(count_vectorizer.vocabulary_))

The number of unique tokens are:  41622


In [20]:
from sklearn.model_selection import cross_val_score

In [23]:
# Now that we have vectorized the data lets try to build the model

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(C=1.0, max_iter=10000)
scores = cross_val_score(lr, train_vectors, y_train, cv=5, scoring="f1")
scores

array([0.88323056, 0.8836095 , 0.88601552, 0.87657029, 0.88376754])

In [ ]:
# The logistic regression provides a very good baseline of about 88%

In [30]:
%%time

lr.fit(train_vectors, y_train)

Wall time: 18 s


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [33]:
y_pred_lr = lr.predict(test_vectors)

In [34]:
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score

f1_score(y_test, y_pred_lr)

0.888280785246877

In [ ]:
# Thus it can be seen that logistic regression provides a very good baseline of about 89% f1 score

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [38]:
tfidf_vectorizer = TfidfVectorizer(min_df=3,analyzer='word',token_pattern=r'\w{1,}',max_df=0.8, use_idf=1,
                                   smooth_idf=1,sublinear_tf=1,stop_words = stopwords)

train_tfidf = tfidf_vectorizer.fit_transform(x_train)
test_tfidft = tfidf_vectorizer.transform(x_test)

In [72]:
test_tfidft = tfidf_vectorizer.transform(x_test)

In [40]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(C=1.0)
scores = cross_val_score(clf, train_tfidf, y_train, cv=5, scoring="f1")
scores

array([0.89544025, 0.89363385, 0.89495549, 0.8834817 , 0.89533965])

In [62]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()

scores_nb = cross_val_score(nb, train_tfidf.toarray(), y_train, cv=5, scoring="f1")
scores_nb

array([0.75341811, 0.80092832, 0.78171362, 0.83703985, 0.8144443 ])

In [63]:
from sklearn.svm import SVC
svc_rbf = SVC(kernel="rbf", C=0.025)

scores_svm = cross_val_score(svc_rbf, train_tfidf, y_train, cv=5, scoring="f1")
scores_svm

array([0.85888363, 0.84231139, 0.88799939, 0.86632048, 0.84008292])

In [70]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=200)

scores_rf = cross_val_score(rfc, train_tfidf, y_train, cv=5, scoring="f1")
scores_rf

array([0.87203167, 0.83356767, 0.85670016, 0.85506362, 0.85884667])

In [ ]:
# Going by the above, it looks like that Logistic Regression has the best performance.

In [ ]:
# Fitting and predicting on lr with tf-idf weights
lr.fit(train_vectors, y_train)